-- CONJUNTO DE INSTRUÇÕES DML 

-- INSTRUÇÃO RESPONSAVÉL POR VISUALIZAR OS ALUNOS DA TABELA
SELECT * FROM ALUNO;
-- INSERIR UM ALUNO, DENTRO DA MINHA TABELA DE ALUNOS
INSERT INTO ALUNO (NOME)
VALUES 
('MILENA DE PAULA MORAES 1'),
('KARINA DOS SANTOS MARTINS 2');


-- INSTRUÇÃO PARA ALTERAR UM ALUNO
UPDATE ALUNO SET NOME = 'MILENA DE PAULA MORAES 10' WHERE ID_ALUNO = 1; 

-- INSTRUÇÃO PARA REMOVER UM ALUNO
DELETE FROM ALUNO WHERE ID_ALUNO = 1;

