-- MySQL Script generated by MySQL Workbench
-- Wed Apr  6 14:40:20 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema my_checkpoint2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema my_checkpoint2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `my_checkpoint2` DEFAULT CHARACTER SET utf8 ;
USE `my_checkpoint2` ;

-- -----------------------------------------------------
-- Table `my_checkpoint2`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_checkpoint2`.`CLIENTE` (
  `ID_CLIENTE` INT NOT NULL AUTO_INCREMENT,
  `NOME_CLIENTE` VARCHAR(60) NULL,
  `TELEFONE_CLIENTE` INT (50) ,
  `EMAIL_CLIENTE` VARCHAR(50) NULL,
  `CPF_CLIENTE` VARCHAR(50) NULL,
  PRIMARY KEY (`ID_CLIENTE`)
  ) ENGINE = InnoDB; 


-- -----------------------------------------------------
-- Table `my_checkpoint2`.`PEDIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_checkpoint2`.`PEDIDO` (
  `ID_PEDIDO` INT NOT NULL AUTO_INCREMENT,
  `DATA_HORA` DATETIME NULL,
  `TAXA_ENTREGA` NCHAR NULL,
  `CLIENTE_ID_CLIENTE` INT NOT NULL,
  PRIMARY KEY (`ID_PEDIDO`),
  INDEX `fk_PEDIDO_CLIENTE1_idx` (`CLIENTE_ID_CLIENTE` ASC) VISIBLE,
  CONSTRAINT `fk_PEDIDO_CLIENTE1`
    FOREIGN KEY (`CLIENTE_ID_CLIENTE`)
    REFERENCES `my_checkpoint2`.`CLIENTE` (`ID_CLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_checkpoint2`.`DOCERIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_checkpoint2`.`DOCERIA` (
  `ID_DOCERIA` INT NOT NULL,
  `SABOR_DOCES` VARCHAR(50) NULL,
  `SABOR_RECHEIO` VARCHAR(50) NULL,
  `ACOMPANHAMENTO` VARCHAR(50) NULL,
  PRIMARY KEY (`ID_DOCERIA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_checkpoint2`.`PEDIDO_DOCERIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_checkpoint2`.`PEDIDO_DOCERIA` (
  `ID_PEDIDO_DOCERIA` INT NOT NULL,
  `QUANTIDADE` INT NULL,
  `VALOR` NCHAR NULL,
  `PEDIDO_ID_PEDIDO` INT NOT NULL,
  `DOCERIA_ID_DOCERIA` INT NOT NULL,
  PRIMARY KEY (`ID_PEDIDO_DOCERIA`),
  INDEX `fk_PEDIDO_DOCERIA_PEDIDO_idx` (`PEDIDO_ID_PEDIDO` ASC) VISIBLE,
  INDEX `fk_PEDIDO_DOCERIA_DOCERIA1_idx` (`DOCERIA_ID_DOCERIA` ASC) VISIBLE,
  CONSTRAINT `fk_PEDIDO_DOCERIA_PEDIDO`
    FOREIGN KEY (`PEDIDO_ID_PEDIDO`)
    REFERENCES `my_checkpoint2`.`PEDIDO` (`ID_PEDIDO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PEDIDO_DOCERIA_DOCERIA1`
    FOREIGN KEY (`DOCERIA_ID_DOCERIA`)
    REFERENCES `my_checkpoint2`.`DOCERIA` (`ID_DOCERIA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_checkpoint2`.`ENDERECO_CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_checkpoint2`.`ENDERECO_CLIENTE` (
  `ID_ENDERECO_CLIENTE` INT NOT NULL,
  `RUA` VARCHAR(50) NULL,
  `BAIRRO` VARCHAR(50) NULL,
  `CIDADE` VARCHAR(50) NULL,
  `ESTADO` VARCHAR(50) NULL,
  `NUMERO_CASA` INT NULL,
  `CLIENTE_ID_CLIENTE` INT NOT NULL,
  PRIMARY KEY (`ID_ENDERECO_CLIENTE`),
  INDEX `fk_ENDERECO_CLIENTE_CLIENTE1_idx` (`CLIENTE_ID_CLIENTE` ASC) VISIBLE,
  CONSTRAINT `fk_ENDERECO_CLIENTE_CLIENTE1`
    FOREIGN KEY (`CLIENTE_ID_CLIENTE`)
    REFERENCES `my_checkpoint2`.`CLIENTE` (`ID_CLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
