CREATE DATABASE my_checkpoint2;

USE my_checkpoint2;

SELECT * FROM cliente;

INSERT INTO cliente(NOME_CLIENTE, TELEFONE_CLIENTE, EMAIL_CLIENTE,CPF_CLIENTE)
VALUES ('MILENA', '953322344', 'MILENAMORAESRC@GMAIL.COM', '46857152845');

UPDATE cliente SET NOME_CLIENTE = 'MILENA MORAES'
WHERE NOME_CLIENTE = 'MILENA';

DELETE FROM cliente WHERE ID_CLIENTE = 3;

SELECT CPF_CLIENTE
FROM cliente;


